export enum SHORTCUTS_ALIASES {
    // NAVIGATION
    MY_DAY = 'my day',
    BACK = 'back',
    FORWARD = 'forward',

    // SYSTEM-WIDE
    QUICK_CAPTURE = 'open quick capture',

    // APP-WIDE
    NEW_DOCUMENT = 'new page',
    NEW_PROJECT = 'new folder',
    OPEN_SETTINGS = 'open settings',
    OPEN_SEARCH = 'open search',
    OPEN_FULL_SEARCH = 'open full search',
    OPEN_XRAY = 'open xray',

    // TABS
    TABS_NEW = 'tab: new tab',
    TABS_CLOSE = 'tab: close current tab',
    TABS_ACTIVATE_NEXT_TAB = 'tab: focus next tab',
    TABS_ACTIVATE_NEXT_TAB_DEFAULT = 'tab: focus next tab default',
    TABS_ACTIVATE_PREVIUOS_TAB = 'tab: focus previous tab',
    TABS_ACTIVATE_PREVIUOS_TAB_DEFAULT = 'tab: focus previous tab default',
    TABS_ACTIVATE_1 = 'tab: activate tab 1',
    TABS_ACTIVATE_2 = 'tab: activate tab 2',
    TABS_ACTIVATE_3 = 'tab: activate tab 3',
    TABS_ACTIVATE_4 = 'tab: activate tab 4',
    TABS_ACTIVATE_5 = 'tab: activate tab 5',
    TABS_ACTIVATE_6 = 'tab: activate tab 6',
    TABS_ACTIVATE_7 = 'tab: activate tab 7',
    TABS_ACTIVATE_8 = 'tab: activate tab 8',
    TABS_ACTIVATE_9 = 'tab: activate tab 9',
    TABS_ACTIVATE_10 = 'tab: activate tab 10',
    TABS_CYCLE_GROUP = 'tab: focus next tab group',
    TABS_CYCLE_GROUP_REVERSE = 'tab: focus previous tab group',
    // MY DAY
    MY_DAY_TODAY = 'my day: today',
    MY_DAY_NEXT_DAY = 'my day: next day',
    MY_DAY_PREVIOUS_DAY = 'my day: previous day',

    // REVIEW-PANEL
    REVIEW_PANEL_TOGGLE = 'review: toggle overdue',
    REVIEW_PANEL_DOWN = 'review: down',
    REVIEW_PANEL_UP = 'review: up',

    // PAGE
    SHARE = 'share page',
    OPEN_DOCUMENT_SEARCH = 'find in page',
    OPEN_JIRA_SEARCH = 'find in issues',
    PAGE_CLEAR_DATE = 'page: clear date',

    // EDITOR
    CONVERT_TO_TASK = 'convert to: convert to task',
    CONVERT_TO_DOCUMENT = 'convert to: convert to document',

    // JIRA
    JIRA_APP = 'jira: open jira app',
    JIRA_UP = 'jira: up',
    JIRA_DOWN = 'jira: down',
    JIRA_STATUS = 'jira: change status',
    JIRA_ASSIGNEE = 'jira: change assignee',
    JIRA_PRIORITY = 'jira: change priority',
    JIRA_PREVIEW = 'jira: preview issue',
    JIRA_CREATE_PAGE = 'jira: create page from issue',
    JIRA_LABELS = 'jira: change labels',

    // LINEAR
    LINEAR_APP = 'linear: open linear app',
    LINEAR_UP = 'linear: up',
    LINEAR_DOWN = 'linear: down',
    LINEAR_STATE = 'linear: change state',
    LINEAR_ASSIGNEE = 'linear: change assignee',
    LINEAR_PRIORITY = 'linear: change priority',
    LINEAR_LABELS = 'linear: change labels',
    LINEAR_PROJECT = 'linear: change project',
    LINEAR_CREATE_PAGE = 'linear: create page from issue',

    // TASKS
    JIRA_GROUP_UP = 'group up',
    JIRA_GROUP_DOWN = 'group down',
    JIRA_COLLAPSE = 'tasks: collapse',
    TASKS_COMPLETE = 'tasks: complete',
    TASKS_TODAY = 'tasks: today',
    TASKS_TOMORROW = 'tasks: tomorrow',
    TASKS_START_OF_NEXT_WEEK = 'tasks: start of next week',
    TASKS_DELETE = 'tasks: delete task',
    TASKS_ACTIONS_DETAIL = 'tasks: show detail',
    TASKS_ACTIONS_NAVIGATE = 'tasks: navigate to task',
    BLUR = 'blur',

    // NOTIFICATIONS
    TASK_NOTIFICATION_ACCEPT = 'task: notification accept',

    // JIRA
    JIRA_TODAY = 'jira: today',
    JIRA_TOMORROW = 'jira: tomorrow',
    JIRA_START_OF_NEXT_WEEK = 'jira: start of next week',
    JIRA_CUSTOM_DATE = 'jira: select custom date',

    TOGGLE_SIDEBAR = 'toggle sidebar',
    PANEL_INFO = 'panel: page info',
    PANEL_TIMELINE = 'panel: toggle timeline',

    // VIEWS
    VIEWS_ACTIVATE_1 = 'activate view 1',
    VIEWS_ACTIVATE_2 = 'activate view 2',
    VIEWS_ACTIVATE_3 = 'activate view 3',
    VIEWS_ACTIVATE_4 = 'activate view 4',
    VIEWS_ACTIVATE_5 = 'activate view 5',
    VIEWS_ACTIVATE_6 = 'activate view 6',
    VIEWS_ACTIVATE_7 = 'activate view 7',
    VIEWS_ACTIVATE_8 = 'activate view 8',
    VIEWS_ACTIVATE_9 = 'activate view 9',
    VIEWS_ACTIVATE_10 = 'activate view 10',

    VIEW_UP = 'view: up',
    VIEW_DOWN = 'view: down',
    VIEW_GROUP_UP = 'view: group up',
    VIEW_GROUP_DOWN = 'view: group down',
    VIEW_COLLAPSE_SECTION = 'view: collapse',
    VIEW_ARCHIVE_PAGE = 'view: archive page',
    VIEW_DELETE_PAGE = 'view: delete page',
    VIEW_PAGE_DETAIL = 'view: show detail',
    VIEW_PAGE_OPEN = 'view: open page',
    VIEW_STATUS = 'view: change status',

    SEARCH_NEXT = 'search: next result',
    SEARCH_PREVIOUS = 'search: previous result',
    SEARCH_OPEN_RESULT = 'search: open result',
    SEARCH_OPEN_RESULT_NEW_TAB = 'search: open result in new tab',
    SEARCH_CLOSE = 'search: close modal',
    SEARCH_CYCLE_TAB = 'search: cycle tab',

    GITHUB_APP = 'github: open github app',
}

export const KEYBINDS = {
    [SHORTCUTS_ALIASES.JIRA_APP]: {
        keybind: 'meta+shift+j',
        namespace: 'always-active',
        category: 'navigation',
        displayLabel: 'Jira',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.GITHUB_APP]: {
        keybind: 'meta+shift+g',
        namespace: 'always-active',
        category: 'navigation',
        displayLabel: 'Github',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.MY_DAY_TODAY]: {
        keybind: 't',
        namespace: 'overview & editor-inactive',
        category: 'navigation-my-day',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.PANEL_TIMELINE]: {
        keybind: 'meta+shift+i',
        namespace: 'overview & editor-inactive',
        category: 'navigation-my-day',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.MY_DAY_NEXT_DAY]: {
        keybind: 'arrowright',
        namespace: 'overview & editor-inactive',
        category: 'navigation-my-day',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.MY_DAY_PREVIOUS_DAY]: {
        keybind: 'arrowleft',
        namespace: 'overview & editor-inactive',
        category: 'navigation-my-day',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.REVIEW_PANEL_TOGGLE]: {
        keybind: 'meta+shift+o',
        namespace: 'always-active',
        category: 'navigation-my-day',
        displayLabel: 'Toggle Review',
        searchable: false,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.OPEN_SEARCH]: {
        keybind: 'meta+k',
        namespace: 'always-active',
        category: 'navigation',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.OPEN_FULL_SEARCH]: {
        keybind: 'meta+shift+k',
        namespace: 'always-active',
        category: 'navigation',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.OPEN_XRAY]: {
        keybind: 'meta+shift+l',
        namespace: 'always-active',
        category: 'navigation',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.OPEN_SETTINGS]: {
        keybind: 'meta+,',
        namespace: 'always-active & editor-inactive',
        category: 'navigation',
        displayLabel: 'Open Settings',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TOGGLE_SIDEBAR]: {
        keybind: 'meta+/',
        namespace: 'always-active',
        category: 'navigation',
        displayLabel: 'Toggle Sidebar',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.QUICK_CAPTURE]: {
        keybind: 'meta+shift+space',
        namespace: 'system-shortcuts',
        category: 'system-shortcuts',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.BACK]: {
        keybind: ['meta+[', 'MouseButton4'],
        namespace: 'always-active',
        category: 'navigation',
    },
    [SHORTCUTS_ALIASES.FORWARD]: {
        keybind: ['meta+]', 'MouseButton5'],
        namespace: 'always-active',
        category: 'navigation',
    },
    [SHORTCUTS_ALIASES.OPEN_DOCUMENT_SEARCH]: {
        keybind: 'meta+f',
        namespace: 'always-active',
        category: 'core',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.OPEN_JIRA_SEARCH]: {
        keybind: 'meta+f',
        namespace: 'always-active & jira',
        category: 'core',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.NEW_DOCUMENT]: {
        keybind: 'meta+n',
        namespace: 'always-active',
        category: 'create',
        displayLabel: 'New Page',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.NEW_PROJECT]: {
        keybind: 'meta+shift+n',
        namespace: 'always-active',
        category: 'create',
        displayLabel: 'New Folder',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.PANEL_INFO]: {
        keybind: 'meta+shift+i',
        namespace: 'always-active',
        category: 'core',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.REVIEW_PANEL_UP]: {
        keybind: 'arrowup',
        namespace: ['review-panel & overview', 'dropdown'],
        category: 'review',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.REVIEW_PANEL_DOWN]: {
        keybind: 'arrowdown',
        namespace: ['review-panel & overview', 'dropdown'],
        category: 'review',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.JIRA_UP]: {
        keybind: 'arrowup',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.JIRA_DOWN]: {
        keybind: 'arrowdown',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.JIRA_STATUS]: {
        keybind: 's',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.JIRA_ASSIGNEE]: {
        keybind: 'a',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.JIRA_PRIORITY]: {
        keybind: 'p',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.JIRA_PREVIEW]: {
        keybind: ['space', 'enter'],
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.JIRA_CREATE_PAGE]: {
        keybind: 'shift+enter',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.JIRA_LABELS]: {
        keybind: 'l',
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.JIRA_GROUP_UP]: {
        keybind: 'alt+arrowup',
        namespace: 'jira',
        category: 'jira',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.JIRA_GROUP_DOWN]: {
        keybind: 'alt+arrowdown',
        namespace: 'jira',
        category: 'jira',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.JIRA_COLLAPSE]: {
        keybind: ['arrowleft', 'arrowright', 'space'],
        namespace: 'jira & editor-inactive',
        category: 'jira',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.TASKS_COMPLETE]: {
        keybind: 'x',
        namespace: [
            'task-panel & editor-inactive',
            'review-panel & editor-inactive & overview',
            'context-menu',
            'dropdown',
            'view & editor-inactive',
        ],
        category: 'tasks',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TASKS_TODAY]: {
        keybind: 't',
        namespace: [
            'task-panel & editor-inactive',
            'review-panel & editor-inactive & overview',
            'context-menu',
            'dropdown',
        ],
        category: 'tasks',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TASKS_TOMORROW]: {
        keybind: 'r',
        namespace: [
            'task-panel & editor-inactive',
            'review-panel & editor-inactive & overview',
            'context-menu',
            'dropdown',
        ],
        category: 'tasks',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TASKS_START_OF_NEXT_WEEK]: {
        keybind: 'm',
        namespace: [
            'task-panel & editor-inactive',
            'review-panel & editor-inactive & overview',
            'context-menu',
            'dropdown',
        ],
        category: 'tasks',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TASKS_DELETE]: {
        keybind: 'd',
        namespace: [
            'task-panel & editor-inactive',
            'review-panel & editor-inactive & overview',
            'context-menu',
            'dropdown',
        ],
        category: 'tasks',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TASKS_ACTIONS_DETAIL]: {
        keybind: 'space',
        namespace: ['dropdown', 'review-panel & editor-inactive & overview'],
        category: 'tasks',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.TASKS_ACTIONS_NAVIGATE]: {
        keybind: 'enter',
        namespace: [
            'dropdown',
            'review-panel & editor-inactive & overview',
            'view & editor-inactive',
        ],
        category: 'tasks',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.CONVERT_TO_DOCUMENT]: {
        keybind: 'alt+d',
        namespace: 'convert-to',
        category: 'convert-to',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.CONVERT_TO_TASK]: {
        keybind: 'alt+t',
        namespace: 'convert-to',
        category: 'convert-to',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.SHARE]: {
        keybind: 'meta+p',
        namespace: 'always-active',
        category: 'core',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.PAGE_CLEAR_DATE]: {
        keybind: 'c',
        namespace: ['review-panel & overview', 'dropdown'],
        category: 'review',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.BLUR]: {
        keybind: 'escape',
        namespace: ['task-panel & editor-inactive', 'view & editor-inactive'],
        category: 'tasks-tab',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.TASK_NOTIFICATION_ACCEPT]: {
        keybind: 'shift+enter',
        namespace: 'notifications',
        category: 'create',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.TABS_NEW]: {
        keybind: 'meta+t',
        namespace: 'always-active',
        category: 'tabs',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TABS_CLOSE]: {
        keybind: 'meta+w',
        namespace: 'always-active',
        category: 'tabs',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_NEXT_TAB]: {
        keybind: 'meta+shift+]',
        namespace: 'always-active',
        category: 'tabs',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_NEXT_TAB_DEFAULT]: {
        keybind: 'ctrl+tab',
        namespace: 'always-active',
        category: 'tabs',
        configurable: false,
        notAllowed: ['web'],
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_PREVIUOS_TAB]: {
        keybind: 'meta+shift+[',
        namespace: 'always-active',
        category: 'tabs',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_PREVIUOS_TAB_DEFAULT]: {
        keybind: 'ctrl+shift+tab',
        namespace: 'always-active',
        category: 'tabs',
        configurable: false,
        notAllowed: ['web'],
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_1]: {
        keybind: 'meta+1',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_2]: {
        keybind: 'meta+2',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_3]: {
        keybind: 'meta+3',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_4]: {
        keybind: 'meta+4',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_5]: {
        keybind: 'meta+5',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_6]: {
        keybind: 'meta+6',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_7]: {
        keybind: 'meta+7',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_8]: {
        keybind: 'meta+8',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_9]: {
        keybind: 'meta+9',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_ACTIVATE_10]: {
        keybind: 'meta+0',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_1]: {
        keybind: 'meta+ctrl+1',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_2]: {
        keybind: 'meta+ctrl+2',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_3]: {
        keybind: 'meta+ctrl+3',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_4]: {
        keybind: 'meta+ctrl+4',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_5]: {
        keybind: 'meta+ctrl+5',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_6]: {
        keybind: 'meta+ctrl+6',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_7]: {
        keybind: 'meta+ctrl+7',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_8]: {
        keybind: 'meta+ctrl+8',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_9]: {
        keybind: 'meta+ctrl+9',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.VIEWS_ACTIVATE_10]: {
        keybind: 'meta+ctrl+0',
        namespace: 'always-active',
        category: 'tabs',
    },
    [SHORTCUTS_ALIASES.TABS_CYCLE_GROUP]: {
        keybind: 'alt+tab',
        namespace: 'always-active',
        category: 'tabs',
        configurable: true,
        notAllowed: ['windows', 'linux', 'web'],
    },
    [SHORTCUTS_ALIASES.TABS_CYCLE_GROUP_REVERSE]: {
        keybind: 'alt+shift+tab',
        namespace: 'always-active',
        category: 'tabs',
        configurable: true,
        notAllowed: ['windows', 'linux', 'web'],
    },
    [SHORTCUTS_ALIASES.JIRA_TODAY]: {
        keybind: 't',
        namespace: ['context-menu', 'dropdown'],
        category: 'jira',
    },
    [SHORTCUTS_ALIASES.JIRA_TOMORROW]: {
        keybind: 'r',
        namespace: ['context-menu', 'dropdown'],
        category: 'jira',
    },
    [SHORTCUTS_ALIASES.JIRA_START_OF_NEXT_WEEK]: {
        keybind: 'm',
        namespace: ['context-menu', 'dropdown'],
        category: 'jira',
    },
    [SHORTCUTS_ALIASES.JIRA_CUSTOM_DATE]: {
        keybind: 's',
        namespace: ['context-menu', 'dropdown'],
        category: 'jira',
    },
    [SHORTCUTS_ALIASES.SEARCH_NEXT]: {
        keybind: 'arrowdown',
        namespace: ['modal'],
        category: 'search-modal',
    },
    [SHORTCUTS_ALIASES.SEARCH_PREVIOUS]: {
        keybind: 'arrowup',
        namespace: ['modal'],
        category: 'search-modal',
    },
    [SHORTCUTS_ALIASES.SEARCH_OPEN_RESULT]: {
        keybind: 'enter',
        namespace: ['modal'],
        category: 'search-modal',
    },
    [SHORTCUTS_ALIASES.SEARCH_OPEN_RESULT_NEW_TAB]: {
        keybind: 'alt+enter',
        namespace: ['modal'],
        category: 'search-modal',
    },
    [SHORTCUTS_ALIASES.SEARCH_CLOSE]: {
        keybind: 'escape',
        namespace: ['modal'],
        category: 'search-modal',
    },
    [SHORTCUTS_ALIASES.SEARCH_CYCLE_TAB]: {
        keybind: ['tab', 'meta+shift+]', 'meta+shift+['],
        namespace: ['modal'],
        category: 'search-modal',
    },
    [SHORTCUTS_ALIASES.VIEW_UP]: {
        keybind: 'arrowup',
        namespace: 'view & editor-inactive',
        category: 'view-tab',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_DOWN]: {
        keybind: 'arrowdown',
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_GROUP_UP]: {
        keybind: 'alt+arrowup',
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_GROUP_DOWN]: {
        keybind: 'alt+arrowdown',
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_COLLAPSE_SECTION]: {
        keybind: ['arrowleft', 'arrowright', 'space'],
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_ARCHIVE_PAGE]: {
        keybind: ['delete', 'backspace'],
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_DELETE_PAGE]: {
        keybind: ['shift+delete', 'shift+backspace'],
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_PAGE_DETAIL]: {
        keybind: 'space',
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_PAGE_OPEN]: {
        keybind: 'enter',
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.VIEW_STATUS]: {
        keybind: 's',
        namespace: 'view & editor-inactive',
        category: 'view',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.LINEAR_APP]: {
        keybind: 'meta+shift+l',
        namespace: 'always-active',
        category: 'navigation',
        displayLabel: 'Linear',
        searchable: true,
        configurable: true,
    },
    [SHORTCUTS_ALIASES.LINEAR_UP]: {
        keybind: 'arrowup',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.LINEAR_DOWN]: {
        keybind: 'arrowdown',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: false,
    },
    [SHORTCUTS_ALIASES.LINEAR_STATE]: {
        keybind: 's',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.LINEAR_ASSIGNEE]: {
        keybind: 'a',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.LINEAR_PRIORITY]: {
        keybind: 'p',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.LINEAR_LABELS]: {
        keybind: 'l',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.LINEAR_PROJECT]: {
        keybind: 'shift+p',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: true,
    },
    [SHORTCUTS_ALIASES.LINEAR_CREATE_PAGE]: {
        keybind: 'shift+enter',
        namespace: 'linear & editor-inactive',
        category: 'linear',
        configurable: true,
    },
} as Record<SHORTCUTS_ALIASES, any>;
