export const keyToCode = {
    '0': 'Digit0',
    '1': 'Digit1',
    '2': 'Digit2',
    '3': 'Digit3',
    '4': 'Digit4',
    '5': 'Digit5',
    '6': 'Digit6',
    '7': 'Digit7',
    '8': 'Digit8',
    '9': 'Digit9',
    '`': 'Backquote',
    '-': 'Minus',
    '=': 'Equal',
    '\\': 'Backslash',
    ']': 'BracketRight',
    '[': 'BracketLeft',
    p: 'KeyP',
    o: 'KeyO',
    i: 'KeyI',
    u: 'KeyU',
    y: 'KeyY',
    t: 'KeyT',
    r: 'KeyR',
    e: 'KeyE',
    w: 'KeyW',
    q: 'KeyQ',
    a: 'KeyA',
    s: 'KeyS',
    d: 'KeyD',
    f: 'KeyF',
    g: 'KeyG',
    h: 'KeyH',
    j: 'KeyJ',
    k: 'KeyK',
    l: 'KeyL',
    ';': 'Semicolon',
    "'": 'Quote',
    '/': 'Slash',
    '.': 'Period',
    ',': 'Comma',
    m: 'KeyM',
    n: 'KeyN',
    b: 'KeyB',
    v: 'KeyV',
    c: 'KeyC',
    x: 'KeyX',
    z: 'KeyZ',
} as Record<string, string>;

export const keyboardMap = {
    // SPECIAL KEYS MAP
    8: 'backspace',
    9: 'tab',
    13: 'enter',
    16: 'shift',
    17: 'ctrl',
    18: 'alt',
    20: 'capslock',
    27: 'esc',
    32: 'space',
    33: 'pageup',
    34: 'pagedown',
    35: 'end',
    36: 'home',
    37: 'arrowleft',
    38: 'arrowup',
    39: 'arrowright',
    40: 'arrowdown',
    45: 'ins',
    46: 'del',
    91: 'meta',
    93: 'meta',
    224: 'meta',

    // KEYCODE MAP
    106: '*',
    107: '+',
    109: '-',
    110: '.',
    111: '/',
    186: ';',
    187: '=',
    188: ',',
    189: '-',
    190: '.',
    191: '/',
    192: '`',
    219: '[',
    220: '\\',
    221: ']',
    222: "'",
} as Record<number, string>;

// f1-f19 keys
for (let i = 1; i < 20; ++i) {
    keyboardMap[111 + i] = 'f' + i;
}

// numpad
for (let i = 0; i <= 9; ++i) {
    keyboardMap[i + 96] = i.toString();
}
